### ISSUE TITLE
Sea Bitch vs Sea Bitch

### ISSUE THREAD

**Issue by TheTank89** [throneteki/throneteki#1904]
So I played HoD Naggas Ribs. My opponent used Sea Bitch in challenges to take control of NR. I used my Sea Bitch to take control back of NR (because he wanted to Remember the North with it). 

At the end of the phase, my opponent unexpectedly gained control of NR. Hilarious, but not what should happen I guess?

**Comment by jeremylarner** [comment]
I'm guessing this is because:
a) lasting effects unapply in the order they were played, and
b) take control effects return the character to the previous character when they unapply

So B takes control of A's Character X (prev controller was A).
A takes control of X (prev controller was B).
Both effects expire at the same time, and game unapplies them in the order they were applied.
So game gives control to A (doesn't do anything)
Then the game gives control to B, so B ends up with control.
