### ISSUE TITLE
To Go Forward You Must Go Back

### ISSUE THREAD

**Issue by Redal59** [throneteki/throneteki#2017]
While we are waiting some official confirmation from FFG as to if they intend this card to actually work as it is written for the time being is it possible to implement it as per the rules? 

To be specific that means that shuffling your hand is part of the cost and therefore this event can be both your only card in hand and means it will not hit the discard pile but be shuffled with any other cards in hand back into your deck.  If it is cancelled you will then draw no cards and be left with an empty hand. 

At the moment As the only card in hand it just discards itself when played.

**Comment by zacchiro** [comment]
My 0.02 EUR: given we're waiting for official ruling, we shouldn't change the current behavior. It's as arbitrary as what you suggest to do instead.

**Comment by ystros** [comment]
The current behavior is also easier to correct manually - drag the card from discard to your deck, shuffle. There is a chance you would have redrawn it after the shuffle, so this isn't perfect, but it at least corrects the end state. In the empty hand scenario, you could move it to the deck, shuffle, and use the `/draw 5` command.

If we change the current behavior, there is no good way of manually correcting it if FFG rules the other way.  It would get shuffled into your deck, you'd have to fish it out to place in discard (a bit more painful than just moving the top of the discard pile over to draw), then reshuffle since you looked at your deck.

So I think waiting for a ruling would be more prudent.

**Comment by imrahil327** [comment]
New ruling confirmed!

**Comment by ystros** [comment]
Per the errata in FAQ v1.4, shuffling your hand is no longer a cost for the ability but part of the effect. Therefore TGFYMGB doesn't get shuffled in, and I think our implementation is now correct. Please re-open if there are other issues with the card.
