### ISSUE TITLE
Obella Sand + Ward

### ISSUE THREAD

**Issue by mplain** [throneteki/throneteki#2052]
I use Ward to take control of Obella Sand, kill her for military claim. My opponent should be prompted to trigger Obella's ability, but this does not happen.

See FAQ entry: https://thronesdb.com/card/10010

**Comment by ystros** [comment]
Thanks for the report! So far I haven't been able to reproduce this. I got an opportunity to trigger her ability after she was killed for claim while Warded:
![screen shot 2018-06-26 at 2 42 06 am](https://user-images.githubusercontent.com/145077/41903621-3f99d31e-78eb-11e8-9587-6ab218536cae.png)

Since you were playing Stark, did you happen to have Winterfell out to prevent card abilities from triggering?

**Comment by mplain** [comment]
Was playing against a new player (teaching throneteki), he said he was not prompted to trigger Obella, but he might just have being mistaken. If you cannot reproduce it, then it is probably not an issue. Thanks.

**Comment by zacchiro** [comment]
On Tue, Jun 26, 2018 at 03:43:53AM -0700, mplain wrote:
> Was playing against a new player (teaching throneteki), he said he was
> not prompted to trigger Obella, but he might just have being
> mistaken. If you cannot reproduce it, then it is probably not an
> issue. Thanks.

I've seen this kind of feedback from new players too.

My understanding is that people do not really understand that, when
asked for actions/reactions, they should look for the cards that are
currently highlighted, and click on them. I can see how, especially when
the board is large enough, one might overlook that.

It calls for even more explicit visual clues, in addition to
highlighting, but I'm not entirely sure what. Maybe highlighting +
colored border, as we already do for other things, e.g., during
challenges?

Suggestions welcome,
Cheers
