### ISSUE TITLE
Justing pavilion not working on card with Motley attachment 

### ISSUE THREAD

**Issue by luky92** [throneteki/throneteki#2096]
As the issiue states my theory is that adding fool triat somehow removed Knight triat due to timing here is a full recording of the game one of this issue present at  39:50
https://www.useloom.com/share/688fcfde2bf14fbdab567d791b553ca2

**Comment by ystros** [comment]
Thanks for the report, and for including a video! It's really useful to see what's going on.

I noticed your opponent had King Stannis out, who gives -1 STR to non-King characters during power challenges. https://thronesdb.com/card/04067

So when you declared a power challenge with the Knight of Flowers around 39:50, he got +1 STR from your Jousting Pavillion, but -1 STR from King Stannis since he isn't a king. So I don't think this was a bug - there was just so much on the board it was hard to tell what was happening.

Let us know if you find other problems!
