### ISSUE TITLE
False Plans and Hand's Judgment

### ISSUE THREAD

**Issue by egbert86** [throneteki/throneteki#2111]
Hi,

This morning I played a game and when I discarded False Plans from my opponent's hand, the site gave the option to cancel it with The Hand's Judgment, but we both thought I shouldn't be possible. Could you look into that?

Regards,
Egbert

**Comment by DukeTax** [comment]
Thanks for reporting. It is indeed possible to cancel the reaction from False Plans with a Hand's Judgment, and for example also the reactions from recurring events like A Dragon is No Slave. So that should be implemented correctly. If you have any follow-up questions or comments feel free to reply/re-open.
