### ISSUE TITLE
Rickon Stark should allow you to cancel any search effect

### ISSUE THREAD

**Issue by jzimmer91** [throneteki/throneteki#2141]
Currently, you only receive prompts to cancel search effects when your opponent initiates them. However rickon should be able to trigger on any search effect, including your own, which is relevant when comboing him with Robb & Wyman.

E.g.  Trigger my own qohor, sacrifice the attachment, cancel it with Rickon, trigger Robb to stand my board

**Comment by ystros** [comment]
Thanks for the report!

Rules-wise, you're absolutely right - you should be able to cancel your own searches. In practice, though, most decks don't actually want to do this, so always prompting to cancel your own searches would provide a negative experience for those decks. Similarly, you should be able to use Iron Mines to save opponent characters but most of the time, you wouldn't want to, so always prompting in those situations wouldn't make much sense. Thus, we've explicitly restricted such triggers for overall playability in the most amount of decks.

As we (slowly) move closer to having Melee support, these types of interactions will become even more important to be able to be triggered (e.g. temporary alliance with another player, so you want to use an ability to help them that you wouldn't use in a 2-player game).

I've thought about adding an additional account + game level option of prompting in these situations we've currently restricted, defaulting it to off. Turning on the option would allow these abilities to trigger exactly as written on the card, rather than with the artificial restrictions we've put in place for playability.

**Comment by zacchiro** [comment]
Now that the sacrifice dynamics is in full force, it makes a lot of sense to want to sacrifice your own searches to trigger whatever sacrifice reaction, especially if you're using Qohor as agenda.

I've just pushed #2294 to fix this.

**Comment by ystros** [comment]
While I still think an option would be more desirable, it's probably better to turn it always on for now unless there are significant complaints or confusion. Between Qohor and Skagos, this type of usage is becoming more common.
