### ISSUE TITLE
Saving from costs

### ISSUE THREAD

**Issue by chordowa** [throneteki/throneteki#2157]
Actions that use "kill character" as a cost do not allow player to use save interrupts. Maybe it's more comfortable like that as very rarely you want to save characters killed as cost of action, but this is fully legal action that has to be manually implemented, when player wants to do it.

Furthermore, if such save happens to ability with limitation or maximum (we talk about Drowned God Fanatic here) then attempt to use ability fails and does not count toward limit/maximum of uses per time period.

**Comment by mplain** [comment]
This would become relevant if we get any cards with "Kill a character and pay X gold / kneel your faction card", so that canceling one part of the cost would still waste the other part, so that the ability could not be immediately initiated again.

At the moment there is not much sense in attempting to save a character from being killed as a cost, so providing a technical implementation for this should (in my opinion) have lower priority than, say, allowing to not use duplicates to save.

Any fringe cases (you want to get rid of the Risen in hand so that the opponent's Queen Cersei would not gain power for discarding it) could be handled manually / in the chat window, I'd think.

**Comment by chordowa** [comment]
Winning game with Iron Victory does not seem "fringe case" to me. Especially that if I remember correctly, saved attempt of using Drowned God Fanatic does not count toward maximum uses of ability per round so 1 dead Fanatic allows you to transfer almost all (2 per phase) your saves into powers via IV.
Similarly, but with less direct impact, with 6-cost Aeron who allows you to use saves as stands providing you have dead Fanatic.
So it's about being able to trigger your own positive reaction to saves with your own kill effects/costs, which is crucial for this kind of deck.

**Comment by ystros** [comment]
Per the [new FAQ 2.0](https://images-cdn.fantasyflightgames.com/filer_public/0d/5d/0d5d44c0-2352-413b-826b-9fa9b9f187c2/agot_lcg_faq_20.pdf) announced today:

```
(3.2) Saving from a Cost
If a card would leave play as part of the cost of initiating an
ability, that card cannot be saved.
```

Likely to eliminate the scenario above. So once the FAQ goes into effect, the current implementation (allowing no saves) will become correct.
