### ISSUE TITLE
The House of Black and White (Stark)

### ISSUE THREAD

**Issue by Sinoples** [throneteki/throneteki#2223]
Hi team, 

When dominance phase i cannot move gold on location "The House of Black and White". 

Can you see ? 

Thanks :)

**Comment by ystros** [comment]
Thanks for the report!

It's been a few days, but could you provide additional details about this issue? I just tested House of Black and White and it seems to be working properly.

Keep in mind:
1. Since it's an Action ability, it won't prompt you directly. You'll need to turn on the "Dominance phase" action window from your Profile page so that the game pauses to allow you to use the action. Then, you click on the card to open the menu with its action, then click the action in the menu.
2. Per the card text, you cannot just move gold onto the location. You must have enough gold on it to be able to kill a character. Then, you are able to move more gold onto it. If there are no valid targets for the kill, you can't move more gold onto it. See the FAQ here: https://thronesdb.com/card/08022

**Comment by Sinoples** [comment]
Hi Ystros, 

Indeed, I misunderstood the use of this card. So, I can close this issue that is not one.
Thanks for your answer :)
