### ISSUE TITLE
[suggestion] Exchange of Information - the log should say what cards one player gives to another

### ISSUE THREAD

**Issue by mplain** [throneteki/throneteki#2236]
We've been spectating the League final game, and we couldn't see what one player gave to another via Exchange of information. It would be helpful to spectators.

![screenshot_28](https://user-images.githubusercontent.com/7605827/46168556-80217680-c2a1-11e8-881b-769cda296cc6.png)

**Comment by ystros** [comment]
How should this card behave in Melee? The card does not explicitly say to reveal the cards chosen by the opponent, only that you add them to your hand. Is there an implicit requirement to reveal in this scenario that we've missed in the rules?

e.g. 3 player Melee, Player 1 reveals Exchange, chooses Player 2 and reveals the top 10 card. Player 2 chooses the individual cards out of the cards revealed, which are then added to Player 1's hand. Does Player 3 get to know which cards were added to Player 1's hand? (they certainly know the top 10 cards since that's an explicit "reveal")

I agree that it would be handy specifically for spectating - though spectators will be able to see the cards if the "Show hands" option is on. Anticipating future Melee support is part of the reason we hesitated putting it in the log here.

**Comment by mplain** [comment]
You reveal 10 cards, then you choose 1-4 cards to give to the opponent. The cards chosen are still being revealed. The cards not chosen are still being revelaed. It's all open information. Only after choosing and giving are the cards shuffled away, thus ceasing being revealed.

**Comment by ystros** [comment]
Well, that simplifies things. 😄 Thanks!

**Comment by cryogen** [comment]
See, this cards original implementation walks the fine line of “being a memory aid” which I’ve tried to avoid. In my idea world, the cards would become revealed, the selection would be made, and the cards chosen would be put in the log. Maybe.

However, the big inconsistency with cards like this probably means I’ve lost this particular battle
