### ISSUE TITLE
allow controller to inspect cards facedown under Meereen

### ISSUE THREAD

**Issue by zacchiro** [throneteki/throneteki#2298]
Rationale: it should be possible to do so because it is information available to the Meereen controller.

**Comment by mplain** [comment]
In a situation when player A uses Meereen and then player B steals it with Sea Bitch, player B should not be able to see the cards placed under Meereen by player A.

Visibility should be based on who controls the facedown cards, not on who controls Meereen. And since cards under Meereen are not in play, their owner controls them.
