### ISSUE TITLE
Varys's Riddle/Summer Harvest/At Prince Doran's Behest

### ISSUE THREAD

**Issue by ChannelDelibird** [throneteki/throneteki#2331]
Just had a game in which I flipped Harvest to my opponent's Behest, went first, resolved Behest first, opponent flipped Riddle, then I Harvested the Riddle.

As per the Harvest/Riddle interaction (https://thronesdb.com/find?q=summer+harvest) I should have counted 7 gold that turn, but Iron Throne gave me 2. Definitely needs a fix, as it's one that players might easily not know that it's wrong!

**Comment by ystros** [comment]
Thanks for the report! This interaction is actually already documented on the How to Play page under the Specific Card Interactions section, and is not a bug. https://theironthrone.net/how-to-play

For the current implementation on the Iron Throne, whichever plot is resolved last "wins" for Summer Harvest. So if the first player wants the value of X to be 7, they need to resolve Varys's Riddle first (sets X to 2), then Summer Harvest **last** (overwrites X to 7). If they want the value of X to be 2, they need to resolve Summer Harvest first (sets X to 7), and Varys's Riddle last (overwrites X to 2).

It sounds like in your case, you resolved plots in the following order:
* Behest (X not set)
* Harvest (X = 7)
* Riddle (X overwritten to = 2)

This implementation, while not necessarily ideal, allows the first player control over what value X they want. It's written this way because we don't want to automatically choose for the player, and it would be considerable work to explicitly prompt the player to choose from conflicting X values.
