### ISSUE TITLE
Characters are not being sacrificed simultaneously for Return to the Fields

### ISSUE THREAD

**Issue by Odrl7** [throneteki/throneteki#2410]
When you trigger Return to the Fields, I believe the chosen characters are currently being sacrificed sequentially in the order in which you select them, which opens up a reaction window for cards like Wyman Manderly and Catelyn Stark (WotN) even if you choose them to be sacrificed. For instance, if you choose Wyman last, you can trigger him twice and draw two cards before he gets sacrificed himself.

All the characters should be sacrificed simultaneously, and only then should the reaction window open.

**Comment by ystros** [comment]
Thanks for the report! #2431 will have all characters sacrificed simultaneously now for Return to the Fields and other similar cards. Wyman / Catelyn won't be triggerable if they were chosen as one of the three. 

Wyman has a separate bug where it will allow him to be triggered for each card sacrificed instead of just once for the group ("After *1 or more* characters are sacrificed ...") which will need to be addressed separately.
