### ISSUE TITLE
Abilities are highlighting hidden targets

### ISSUE THREAD

**Issue by jzimmer91** [throneteki/throneteki#2778]
When using card effects that target a specific type, all possible information is being shown to the player.  I believe this affects both players, but the most recent example that i encountered was using Halder.  When triggering halder, my deck and discard pile would open up, and i could see highlighted cards in my deck where characters were. 

I'm pretty sure i've encountered a scenario where cards in my opponents hand have been highlighted to me as specific types, but I can not immediately think of what effect caused this to happen.

**Comment by ystros** [comment]
This was probably made worse recently because Friends at Court required us to make facedown cards valid targets for card abilities, and Maester Gorman required us to rework the draw deck interface. So this has made bad targeting implementations more obvious.

Are you aware of any others beyond Halder? Would be great to batch up several bad cards and fix them at one time. If not, just continue to report as you come across them.

**Comment by jzimmer91** [comment]
I thought this one was the case but have confirmed on playing a game - Bound to the wall is highlighting other cards in my opponents deck.

![image](https://user-images.githubusercontent.com/5578368/67508698-65c6f180-f689-11e9-8d3b-1118bbee3f47.png)

**Comment by atkeranov** [comment]
+1
Having Halder highlighting character cards in the deck is huge for the builders match, since the NW player can determine when to play The Watch Has Need and get the most out of it if he decides to abuse the interaction.
![HalderCheatIssue](https://user-images.githubusercontent.com/4188195/81059516-35ce9580-8ed9-11ea-8257-3ca90e57256a.png)

**Comment by ystros** [comment]
Halder has been previously fixed, Bound for the Wall is about to be fixed. Let's close this for now and re-open / file new issues if others are discovered.
