### ISSUE TITLE
Red keep allowing you to cancel your own effects

### ISSUE THREAD

**Issue by jzimmer91** [throneteki/throneteki#2875]
As title, it should only be able to target opponents card effects.  Was noticed when was provided the option to cancel my own haunted forest's forced reaction.

**Comment by EvadLhorg** [comment]
Thank you for the report. If i am not mistaken, The Red Keep and other cancel effects like it will only trigger on forced abilities of your own as those tend to have negative consequences for yourself. So all in all i think this is a feature

**Comment by ystros** [comment]
We implemented Treachery to specifically only trigger on your own abilities if it was forced, since triggering on abilities you initiated would be annoying. Red Keep implementation was copied from that, but the Red Keep says "opponent" specifically, so triggering on your own forced abilities is not correct. 

Fix is on the way.
