### ISSUE TITLE
Randyll Tarly + Knighted + Jousting Pavilion

### ISSUE THREAD

**Issue by jpmckenna90** [throneteki/throneteki#3056]
Hey guys,

Was just playing a game with a Tyrell SoB deck in which I had Randyll on the board with two copies of Knighted on him, and two Jousting Pavilions in play. I declared him as an attacker, his STR was increased by the Jousting Pavilions, but I wasn't prompted to stand him. He had not yet stood in the challenges phase, and as far as I can see, there's nothing that was going on that would've prevented him from standing. Willing to be wrong on this one, but can't see why he wouldn't stand after racking my brain a while. 

![image](https://user-images.githubusercontent.com/27628608/96187493-1bc6c380-0f0b-11eb-9209-6a35efb13775.png)

**Comment by jpmckenna90** [comment]
I'll say it's possible that I blew through the reaction prompt, but I'm 99.9999999% certain this wasn't the case, he knelt and then I wasn't prompted again.

**Comment by EvadLhorg** [comment]
Thank you very much for the awesome bug report and the load of details! Some other people also had this issue in combination with the Lord of the Crossing STR buff on the third challenge and reported it. The fix for this is on the way (https://github.com/throneteki/throneteki/pull/3053) and will be included in the next update!

**Comment by jpmckenna90** [comment]
Awesome, thanks for the quick response and all the work you guys do!

**Comment by cryogen** [comment]
deployed now
