### ISSUE TITLE
Green-Apple Knight (HoT), Jousting Pavilion (HoT) and Highgarden Courtier (HoT) - only when defending?

### ISSUE THREAD

**Issue by Laconda** [throneteki/throneteki#3119]
Hello,

when a knight is **defending** alone, he gets STR+1 from Pavillon and the Courtier can stand him.

Why can't she stand him, when he is **attacking** alone and also gets STR+1? (tried to use her ability first time in the phase)

**Comment by Laconda** [comment]
...and second question: "(Limit once per phase.)" - doesn't this mean per Courtier I have in game? On the website I can use the abilty only with one Courtier per phase. The others can't use their ability anymore, after the first Courtier used it.

If so, is it the same with "Faceless man"? If I have 3 of them in play, only 1 per phase can gain challenge icons, etc.?

**Comment by EvadLhorg** [comment]
Hello!

Regarding the Courtier Bug: It might be the same issue that will be fixed with https://github.com/throneteki/throneteki/pull/3117 this fix.
Regarding the limit: Limit once per phase would be per courtier character, you got that right. So you should be able to use multiple courtiers per phase to stand on different STR increase occasions. I´ve tested it and it seems to work (including the aforementioned fix), so maybe this is a follow up bug of your first bug report.

Feel free to join the community discord here: https://discord.gg/p7KwYYdd
You can ask about general stuff and rules questions there, i think that would be quicker/more responsive than creating github issues.

**Comment by Laconda** [comment]
Thanks for your response and your advice for discord! I just joined.

And yes, it worked for me too this time (regarding the limit).

**Comment by EvadLhorg** [comment]
Can be closed now as #3117 is now deployed on the server @ystros
