### ISSUE TITLE
Stormcrows do not prompt value for X

### ISSUE THREAD

**Issue by dragonfireadept** [throneteki/throneteki#3147]
Game 1: Summoned Stormcrows from discard pile using Targ Tyrion Lannister. Bestowed 4 in challenges phase. Clicked stormcrows to trigger its action. Did not allow you to select value for X. Even when moved to hand and replayed. 

Game 2: played Stormcrows and put gold on it using The Free Companies. Could not select X

stormcrows seems broken where it will not prompt for you to pick a value for X

**Comment by ystros** [comment]
I'm 90% certain your client is out of date. X-value prompts have changed to be a text field instead of individual buttons:

<img width="659" alt="Screen Shot 2021-07-12 at 10 19 10 PM" src="https://user-images.githubusercontent.com/145077/125394992-645ac280-e35f-11eb-887d-d104a51f1773.png">

Try hard-refreshing the site.
