### ISSUE TITLE
The Winter Maid is not returning to hand when opponent just revealed summer, even tho summer was not revealed during the interrupt window

### ISSUE THREAD

**Issue by Duckbringer** [throneteki/throneteki#3176]
Repro steps:
1) start game -> no revelaed plots
2) choose summer plot
3) play winter maid
4) **Problem: winter maid does not return to hand**

**Expected behaviour:**
Winter maid will return to hand UNLESS there was revealed summer plot during the interrupt window.

/-----------------------------

Examples of correct behaviour:

First:
1) start of plot phase, where there isnt summer plot revealed
  2) reveal summer plot
  3) play Winter Maid
  4) winter maid returns to hand

Second:
  1) summer plot revelaed
  2) end of round -> plot phase
  3) choose any plot
  4) play winter maid
  5) winter maid does NOT return to hand

**Comment by ystros** [comment]
I think we need an official ruling, as I'm not sure if this is really a bug. 

Winter Maid is an interrupt to new plots being revealed. Interrupts happen before the triggering condition is in effect; that is, interrupts to plots being revealed happens before they're actually revealed. The wording of the card says to check what plots are revealed, but since it's an interrupt, the new plots are *not* currently revealed. Hence, it would look at plots from the previous round.

It's possible the *intent* of the card is to look for Summer trait on the soon-to-be-revealed plots, but that doesn't seem to be how it's worded based on being an interrupt.

If it were a reaction, it should definitely work the way you've described.

**Comment by ystros** [comment]
Sorry, I misread your comment. You're describing exactly what I did. 😅 

Yes, seems like a bug.

**Comment by Duckbringer** [comment]
The ruling seemed pretty official in design team chat, but i am not sure they released it yet
