### ISSUE TITLE
Plot: Blood of the Dragon + Ser Lancel Lannister

### ISSUE THREAD

**Issue by salsabuster** [throneteki/throneteki#3301]
Plot: Blood of the Dragon  (-1str) + Ser Lancel Lannister (str x) + Ser Bryne Caron (LORD: str 4) : Lancel is killed immediately when marshalled.

This is not correct, both timing is 'GET' not one before the other. Maybe program Blood of the Dragon as a last step ?

**Comment by Patane97** [comment]
I believe this is because Lancel only works when 1 Lannister _**Lord**_ or _**Lady**_ is in play; Ser Bryce Caron is not a Lannister character, and would only provide him +1 STR.

So when Lancel enters play, the calculation would be:
- Lancel gains +1 STR from Ser Bryce Caron's passive
- Lancel gets -1 STR from Blood of the Dragon
Lancel's STR is 0 at the end of the calculation, therefore being killed by the plot.

I might close this issue, but welcome to comment again if you have more details on the situation to change things. 💪
